### ISSUE TITLE
Guidelines and tolerance

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-grid-guide#10]
- When the guidelinesTolerance option is zero (0), I still expect to see the guidelines when there is perfect alignment but I don't!
- When the tolerance is non-zero (e.g. 2), guidelines should still be drawn horizontal or vertical to show where there would be perfect alignment.

**Comment by kinimesi** [comment]
It is very hard to align when tolerance is 0, due to the precision of position values. If you turn on "Show grid", "Snap to grid", "Discrete drag" and "Auto resize" properties and set tolerance to 0, guidelines will show up when there is a perfect alignment.

**Comment by ugurdogrusoz** [comment]
In the old implementation there was a bug and alignment was never detected for tolerance 0. This is no longer an issue. Even without grid and snap to grid disabled I can alignment with 0 tolerance btw (not as easy as when it's 2 but still doable).
