### ISSUE TITLE
Uninitialized cy variable

### ISSUE THREAD

**Issue by tvoloshyn** [iVis-at-Bilkent/cytoscape.js-grid-guide#13]
Hi guys,

I'm getting an error, while trying to include this plugin, registered with "Plain JS" method.

The problem is at line 1025 (probably somewhere else as well). https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide/commit/6fe4bfed49584f9ddfc9c920ed4ae88299cf2892 

`Uncaught ReferenceError: cy is not defined`

I've added a temporary fix by assigning `window.cy` to an instance of cytoscape, but I'd say it has to be changed inside the plugin itself, as not everyone is assigning cytoscape to a `window `object directly.

Thanks

**Comment by metincansiper** [comment]
Thanks @tvoloshyn for identifying the problem. I fixed that problem. If your problem is solved we can close the issue.
