### ISSUE TITLE
Canvas isn't resized on browser resizing

### ISSUE THREAD

**Issue by bastianleirpo** [iVis-at-Bilkent/cytoscape.js-grid-guide#14]
Hello,

grid-guide creates two additional canvas elements above of the cytoscape.js canvas elements. One of the both elements doesn't have any attributes, the other got an absolute position, top, left and z-index attributes. So far, no problem. 
When the browser is resized and due to the layout, several HTML elements wrap, top and left attributes aren't updated like they were on other canvas elements from other cytoscape plugins.
This results in a problematically layout where you may drag and drop the canvas outside of the borders of the desired area. Additionally node's touchpoints are postponed.

Before resizing:
![before](https://cloud.githubusercontent.com/assets/22075788/22418365/0bb5853e-e6d9-11e6-8ece-2a154b4c288d.JPG)

After resizing:
![after](https://cloud.githubusercontent.com/assets/22075788/22418366/0bb5ac30-e6d9-11e6-8b43-4a9a48665a0a.JPG)

**Comment by kinimesi** [comment]
Hi @bastianleirpo I think the problem is fixed now. Can you verify and close the issue? Thanks.

**Comment by bastianleirpo** [comment]
Hey @kinimesi, yes it fixed it. You might remove the console.log output on resizeing.
