### ISSUE TITLE
Option for ignoring center to edge alignments

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-grid-guide#15]
Let's add an option to ignore center to edge alignments of nodes

**Comment by kinimesi** [comment]
Option is added in https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide/commit/4699ed90336e5fd361051eef7a643c3aa2a3fd3b. Center to edge alignments are ignored by default.

Deployed new version to ChiSE_daily, but option is not added to "Grid Properties" menu. We should discuss where to put this option.

**Comment by ugurdogrusoz** [comment]
center to edge alignment option not needed in our editor
