### ISSUE TITLE
Guidelines to initial mouse location

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-grid-guide#17]
Initial mouse location (the location where we clicked on the node to be dragged) should also be remembered and taken into consideration during drag. So the user knows how the drag is proceeding w.r.t. initial mouse position.

**Comment by kinimesi** [comment]
Should there be different color option and On/Off option for this guideline?

I deployed current version to ChiSE_daily. Right now in order to see this guidelines, you need to **enable** "Geometric alignment" from "Grid Properties" menu.

**Comment by ugurdogrusoz** [comment]
Works like a charm, thanks! Yes there should be options (in this extension) for enabling/disabling it and its style (color, dashed or solid, etc.).
