### ISSUE TITLE
Inconsistent inside/outside distribution alignment

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-grid-guide#18]
In the attached model, if you click on the process, both geometric and distribution (inside/middle) guidelines are shown. But if you click on either of the two macromolecules A or B, then only the geometric guideline is shown. Maybe there is a rounding error or something preventing alignment in this case?

[inconsistent-distribution.sbgnml.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide/files/835773/inconsistent-distribution.sbgnml.txt)

**Comment by kinimesi** [comment]
Can't reproduce.
![Guidelines for A](https://cloud.githubusercontent.com/assets/7281872/23824802/156f4cf0-0686-11e7-97c4-079438554e9e.png)
![Guidelines for A](https://cloud.githubusercontent.com/assets/7281872/23824813/3f0a8f98-0686-11e7-9c87-a064cc86c9ad.png)

**Comment by ugurdogrusoz** [comment]
Neither can I. I guess save and load hid the problem. Well I'll close this (at least until I can describe it in a way that's reproducible).
