### ISSUE TITLE
Not enough room for guidelines

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-grid-guide#20]
When there is not enough room for guidelines, it's probably not worth drawing guidelines. See example below (where there isn't enough room for vertical distribution guidelines):
![not-enough-room-for-guideline](https://cloud.githubusercontent.com/assets/3874988/24907422/d3706e72-1ec4-11e7-9f0f-30d29d5ab1ca.png)
So, below a certain length (not long enough to accommodate a line with arrows), they shouldn't be drawn at all (would be best to let the user define this as an extension option).

**Comment by ugurdogrusoz** [comment]
Can we increase the minimum a bit? We still have such situations (assuming latest is on daily):
![image](https://cloud.githubusercontent.com/assets/3874988/24944274/16fda558-1f63-11e7-9ccd-6167d7adbd83.png)

**Comment by kinimesi** [comment]
See https://github.com/iVis-at-Bilkent/newt/commit/7575a9637e39fee58d02a9665a8a7ddd938d8d7d
