### ISSUE TITLE
Initialization pattern if used together with cytoscape.js-context-menus

### ISSUE THREAD

**Issue by shean42** [iVis-at-Bilkent/cytoscape.js-grid-guide#23]
While trying to use grid-guide and context-menus together I ran into the issue that the order of initialization of these extensions is crucial. To be more concrete:

- First initializing context-menus and then grid-guide results in "TypeError: e is null" in cytoscape.js.
- Initializing grid-guide first does not throw that error.

I suspect this is not intentional? :-)

**Comment by ugurdogrusoz** [comment]
@kinimesi Can you please take a look?

**Comment by kinimesi** [comment]
@shean42 Which version of Cytoscape.js are you using?

**Comment by shean42** [comment]
v3.2.3

**Comment by kinimesi** [comment]
@shean42 Do you have the same problem in Cytoscape.js v3.1.5?

**Comment by shean42** [comment]
v3.1.5 does not appear to have that issue!

**Comment by kinimesi** [comment]
@shean42 This was due to a bug is Cytoscape.js, see https://github.com/cytoscape/cytoscape.js/issues/1980. Should be fixed in [v3.2.4](https://github.com/cytoscape/cytoscape.js/releases/tag/v3.2.4). Can you verify and close? Thanks.

**Comment by shean42** [comment]
Solved by v3.2.4, thanks!
