### ISSUE TITLE
Grabbing of ungrabified nodes

### ISSUE THREAD

**Issue by shean42** [iVis-at-Bilkent/cytoscape.js-grid-guide#24]
Ungrabified nodes can be grabbed if option "snapToGridDuringDrag" is set to true.

**Comment by ugurdogrusoz** [comment]
Could this be related to https://github.com/iVis-at-Bilkent/newt/issues/177?

**Comment by kinimesi** [comment]
@shean42 can you verify and close?

**Comment by shean42** [comment]
Solved, thanks!!
