### ISSUE TITLE
"Snap to Grid During Drag" prevents box selection in all nodes

### ISSUE THREAD

**Issue by shean42** [iVis-at-Bilkent/cytoscape.js-grid-guide#28]
This one can be easily tested in the demo.

**Comment by kinimesi** [comment]
@shean42 should be fixed in unstable branch. Can you verify and close? Thanks. [Demo of unstable branch](https://rawgit.com/iVis-at-Bilkent/cytoscape.js-grid-guide/unstable/demo.html)

**Comment by shean42** [comment]
Great, thanks!!
