### ISSUE TITLE
Meet UglifyJs error while building my web code

### ISSUE THREAD

**Issue by bofortitude** [iVis-at-Bilkent/cytoscape.js-grid-guide#30]
Have you ever made some uglifyjs related plugins config in your code?

I tried to compile my web code, but met the error:

ERROR in static/js/vendor.c2fa7ee7f34202a87f40.js from UglifyJs
Unexpected token name «of», expected punc «;» [./node_modules/cytoscape-grid-guide/src/guidelines.js:248,0][static/js/vendor.c2fa7ee7f34202a87f40.js:74852,13]

  Build failed with errors.

npm ERR! code ELIFECYCLE

**Comment by kinimesi** [comment]
@bofortitude `for...of` statement is replaced in release v2.1.1, the issue should be resolved, can you verify and close?
