### ISSUE TITLE
Grid isn't drawn in latest Firefox

### ISSUE THREAD

**Issue by Radobilly** [iVis-at-Bilkent/cytoscape.js-grid-guide#31]
Although i think the issue is related to the latest Firefox version i'd like to point out that the grid isn't drawn in Firefx 59.0.1
Older versions, before Firefox Quantum, seems to work fine.

**Comment by kinimesi** [comment]
@Radobilly I just tried the [demo](https://rawgit.com/iVis-at-Bilkent/cytoscape.js-grid-guide/master/demo.html) in Firefox 59.0.1 (Linux), it works as expected.  Are you using a different OS?
![spectacle j17017](https://user-images.githubusercontent.com/7281872/37830151-a3a0817e-2eb2-11e8-9397-7b28b39fc938.png)

**Comment by kinimesi** [comment]
@Radobilly should be fixed in unstable branch. Can you verify and close? Thanks. [Demo](https://rawgit.com/iVis-at-Bilkent/cytoscape.js-grid-guide/unstable/demo.html)

**Comment by Radobilly** [comment]
Yepp, that solved the issue, thanks! Awesome fix, you rock! <3
