### ISSUE TITLE
TypeError: cy.gridGuide is not a function

### ISSUE THREAD

**Issue by shean42** [iVis-at-Bilkent/cytoscape.js-grid-guide#34]
After [#33]([https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide/issues/33]) there is now the above issue on initialization. After minimizing our project it turns out that the following line called in another external library causes the issue:

if (window.jQuery) { jQuery.noConflict(); } 

Since other plugins, like edgehandles etc., don't have the above issue I wonder if initialization of all plugins should not follow the same pattern, preferably that of plugins without the above issue?!

However, since the hack in [#33]([https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide/issues/33]) still works well for us, this is more a question of general curiosity for now :-)

**Comment by kinimesi** [comment]
This should be fixed with [v2.3.0](https://github.com/iVis-at-Bilkent/cytoscape.js-grid-guide/releases/tag/v2.3.0) since we removed jquery dependency.
