### ISSUE TITLE
Empty style of grid canvas when drawGrid is false

### ISSUE THREAD

**Issue by youyaochi** [iVis-at-Bilkent/cytoscape.js-grid-guide#35]
I noticed that if I set `{drawGrid: false}`, there will be an empty canvas element which cause the whole canvas height higher than it should be.
I'm using `cytoscape@3.2.17` with `cytoscape-grid-guide@2.2.0`.

**Comment by youyaochi** [comment]
To someone encounter this problem, I fixed it by adding this style:
```
#graph > canvas {
    position: absolute; 
    top: 0px; 
    left: 0px;
}
```

**Comment by ugurdogrusoz** [comment]
I thought you said you resolved the problem! Please provide a minimal JS Fiddle which reproduces your problem.

**Comment by youyaochi** [comment]
My bad, thanks for reopening!  
[https://jsfiddle.net/youyaochi/w8qzakre/10/](https://jsfiddle.net/youyaochi/w8qzakre/10/)  
The scroll bar appears!

**Comment by kinimesi** [comment]
@youyaochi should be fixed in the unstable branch. Can you please verify and close? Thanks.

**Comment by kinimesi** [comment]
> To someone encounter this problem, I fixed it by adding this style:
> 
> ```
> #graph > canvas {
>     position: absolute; 
>     top: 0px; 
>     left: 0px;
> }
> ```

This solution would not work properly: turn draw grid on, then turn it off. Now, reduce the size of the browser window, scrollbar will appear.

**Comment by youyaochi** [comment]
I built the unstable branch and it worked perfectly :)
