### ISSUE TITLE
Why was Cytoscape.js dependency updated?

### ISSUE THREAD

**Issue by kinimesi** [iVis-at-Bilkent/cytoscape.js-grid-guide#40]
I realized that Cytoscape.js dependency was updated to 3.3.0 4d36ff8ca5c82ec59ad8dd27e9b961df75df0ecb As far as I know, we have maintained backward compatibility pretty well and it should work with all versions `>=1.6.0`

If backward compatibility will be removed, then it  should be removed from the source code as well. There are a couple of checks and conditions that we use to provide backward compatibility.

**Comment by ugurdogrusoz** [comment]
@kinimesi With so many different versions of Cytoscape.js around, we had difficulty to keep up with errors in many of our extensions. Doesn't look like we'll be able to provide backward compatibility and as you said we should remove any related code.
