### ISSUE TITLE
How to force a grid resize/rerender

### ISSUE THREAD

**Issue by sikula** [iVis-at-Bilkent/cytoscape.js-grid-guide#45]
I'm using this library with ReactJS and my page has the cytoscape graph in the mainview, and a sliding panel on the right.  When the panel is closed, I would like the grid to re-calculate the size and update.  Is there a way to force the grid to resize?

**Comment by sikula** [comment]
Just to be clear, the canvas does resize when the **window** size changes, but not when the size of the parent container changes

**Comment by hasanbalci** [comment]
@sikula This must be fixed in the unstable branch. Can you please verify that it works now? We will make a new release soon if it is ok.

**Comment by sikula** [comment]
That worked! Think so much
