### ISSUE TITLE
Be compliant with JS strict mode

### ISSUE THREAD

**Issue by Jajawah** [iVis-at-Bilkent/cytoscape.js-grid-guide#51]
I'm using a framework enforcing the JS strict mode and I encountering some errors due to some uninitialized variables like 
- calculateOffset in guideline.js 
- padding in parentPadding.js

Is it possible to ensure the respect of the strict mode ?

**Comment by hasanbalci** [comment]
@Jajawah Actually, these errors are fixed in the unstable branch and will be available with the next release. Until then, you can use the unstable branch.

**Comment by ugurdogrusoz** [comment]
@Jajawah please feel free to make a PR to the unstable branch if you like. We currently do not have any resources to work on this.

**Comment by Jajawah** [comment]
I had not seen the related PR... since those erros are already fixed in the unstable branch, that's right for me.
Many thanks !
